### ISSUE TITLE
A vulnerabilitiy with dependency of the package 'debug'

### ISSUE THREAD

**Issue by SugiShio** [nfroidure/plexer#3]
## Issue
This package has dependency on the package debug@debug@2.6.1, but
it is reported to have a vulnerabilitiy of ReDoS.
This is patched in the version >= 2.6.9 < 3.0.0 || >= 3.1.0 .

There might be more dependencies which contain vulnerabilities but I didn't inspect.
Please update the dependencies.

I'm a gentledev i:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked i'm up to date with the latest version of the project

### Actual behavior
With the command `npm audit` at npm@6, a message like this is printed.

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-iconfont [dev]                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-iconfont > gulp-spawn > plexer > debug                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### Steps to reproduce the behavior
Execute `npm audit` at npm@6 on a shell.

### Debugging informations
- `node -v` result:
```
v8.4.0
```

- `npm -v` result:
```
6.2.0
```

Sorry for my poor English.

- [ ] I will/have implement the feature

**Comment by sergeymorkovkin** [comment]
Confirm.

**Comment by dopry** [comment]
@nfroidure any chance you can `npm install debug@latest` and cut a release? gulp-spawn and gulp-iconfont are both affected by this. I know there isn't real exposure here to a regex based DoS in a build process, but it would be nice to clear the errors.

**Comment by nfroidure** [comment]
@dopry would merge any PR doing so and also, would give rw access to that person to publish the changes.

Otherwise, I'll try to find a moment to do so.

**Comment by dopry** [comment]
Not interested in the responsibility of maintainership, but I can cut a PR for you. see: #4

**Comment by dawidgarus** [comment]
Can we get new release any time soon?

**Comment by nfroidure** [comment]
Done.
